In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("TV Shows - Netflix.csv")

In [3]:
df

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+          9.5        1
1                     Game of Thrones  2011    18+          9.3        0
2                      Rick and Morty  2013    18+          9.2        0
3                                Dark  2017    16+          8.8        1
4                     Stranger Things  2016    16+          8.8        1
5          Avatar: The Last Airbender  2005     7+          9.2        1
6                            Sherlock  2010    16+          9.1        1
7                           Chernobyl  2019    18+          9.4        0
8                             Friends  1994    16+          8.9        0
9                          The Office  2005    16+          8.9        1
10                   Better Call Saul  2015    18+          8.7        1
11                           The Wire  2002    18+          9.3        0
12                       Supernatural  2005    16+          8.4        0
13                              Fargo  2014    18+          8.9        0
14                       Black Mirror  2011    18+          8.8        1
15                   Band of Brothers  2001    18+          9.4        0
16                    Attack on Titan  2013    16+          8.8        0
17                              House  2004    16+          8.7        0
18                        Money Heist  2017    18+          8.4        1
19                     Peaky Blinders  2013    18+          8.8        1
20                          Mr. Robot  2015    18+          8.5        0
21                            Vikings  2013    18+          8.5        0
22                       The Sopranos  1999    18+          9.2        0
23                       The Simpsons  1989     7+          8.7        0
24                    The Mandalorian  2019     7+          8.7        0
25                               Lost  2004    16+          8.3        0
26                          Westworld  2016    18+          8.7        0
27               The Umbrella Academy  2019    16+          8.0        1
28                             Narcos  2015    18+          8.8        1
29                     True Detective  2014    18+          9.0        0
30                 Marvel's Daredevil  2015    18+          8.6        1
31                 Brooklyn Nine-Nine  2013    16+          8.4        0
32                   The Walking Dead  2010    18+          8.2        1
33               Parks and Recreation  2009    16+          8.6        0
34                         Mindhunter  2017    18+          8.6        1
35                         South Park  1997    18+          8.7        0
36                              Suits  2011    16+          8.5        0
37                           Hannibal  2013    18+          8.5        1
38                             Dexter  2006    18+          8.6        0
39                          Community  2009     7+          8.5        0
40                             Fringe  2008    16+          8.4        0
41                      Modern Family  2009    16+          8.4        0
42                The Big Bang Theory  2007    16+          8.1        0
43                            Firefly  2002    16+          9.0        0
44                            Mad Men  2007    16+          8.6        0
45   Fullmetal Alchemist: Brotherhood  2009    18+          9.1        0
46                              Ozark  2017    18+          8.4        1
47                        The Witcher  2019    18+          8.2        1
48                            Lucifer  2016    16+          8.2        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [20]:
df['Rating'] == '18+'

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11     True
12    False
13     True
14     True
15     True
16    False
17    False
18     True
19     True
20     True
21     True
22     True
23    False
24    False
25    False
26     True
27    False
28     True
29     True
30     True
31    False
32     True
33    False
34     True
35     True
36    False
37     True
38     True
39    False
40    False
41    False
42    False
43    False
44    False
45     True
46     True
47     True
48    False
49     True
Name: Rating, dtype: bool

In [25]:
Raiting_filter =df['Rating'] == '18+'

In [26]:
df[Raiting_filter]

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+          9.5        1
1                     Game of Thrones  2011    18+          9.3        0
2                      Rick and Morty  2013    18+          9.2        0
7                           Chernobyl  2019    18+          9.4        0
10                   Better Call Saul  2015    18+          8.7        1
11                           The Wire  2002    18+          9.3        0
13                              Fargo  2014    18+          8.9        0
14                       Black Mirror  2011    18+          8.8        1
15                   Band of Brothers  2001    18+          9.4        0
18                        Money Heist  2017    18+          8.4        1
19                     Peaky Blinders  2013    18+          8.8        1
20                          Mr. Robot  2015    18+          8.5        0
21                            Vikings  2013    18+          8.5        0
22                       The Sopranos  1999    18+          9.2        0
26                          Westworld  2016    18+          8.7        0
28                             Narcos  2015    18+          8.8        1
29                     True Detective  2014    18+          9.0        0
30                 Marvel's Daredevil  2015    18+          8.6        1
32                   The Walking Dead  2010    18+          8.2        1
34                         Mindhunter  2017    18+          8.6        1
35                         South Park  1997    18+          8.7        0
37                           Hannibal  2013    18+          8.5        1
38                             Dexter  2006    18+          8.6        0
45   Fullmetal Alchemist: Brotherhood  2009    18+          9.1        0
46                              Ozark  2017    18+          8.4        1
47                        The Witcher  2019    18+          8.2        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [28]:
df[df['Rating'] == '18+']

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+          9.5        1
1                     Game of Thrones  2011    18+          9.3        0
2                      Rick and Morty  2013    18+          9.2        0
7                           Chernobyl  2019    18+          9.4        0
10                   Better Call Saul  2015    18+          8.7        1
11                           The Wire  2002    18+          9.3        0
13                              Fargo  2014    18+          8.9        0
14                       Black Mirror  2011    18+          8.8        1
15                   Band of Brothers  2001    18+          9.4        0
18                        Money Heist  2017    18+          8.4        1
19                     Peaky Blinders  2013    18+          8.8        1
20                          Mr. Robot  2015    18+          8.5        0
21                            Vikings  2013    18+          8.5        0
22                       The Sopranos  1999    18+          9.2        0
26                          Westworld  2016    18+          8.7        0
28                             Narcos  2015    18+          8.8        1
29                     True Detective  2014    18+          9.0        0
30                 Marvel's Daredevil  2015    18+          8.6        1
32                   The Walking Dead  2010    18+          8.2        1
34                         Mindhunter  2017    18+          8.6        1
35                         South Park  1997    18+          8.7        0
37                           Hannibal  2013    18+          8.5        1
38                             Dexter  2006    18+          8.6        0
45   Fullmetal Alchemist: Brotherhood  2009    18+          9.1        0
46                              Ozark  2017    18+          8.4        1
47                        The Witcher  2019    18+          8.2        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [29]:
df[df['IMDB_Rating']==8.8]

                               Titles  Year Rating  IMDB_Rating  Netflix
3                                Dark  2017    16+          8.8        1
4                     Stranger Things  2016    16+          8.8        1
14                       Black Mirror  2011    18+          8.8        1
16                    Attack on Titan  2013    16+          8.8        0
19                     Peaky Blinders  2013    18+          8.8        1
28                             Narcos  2015    18+          8.8        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [30]:
df[(df['IMDB_Rating']==8.8) & (df['Rating']== '18+') & (df['Year']== 2013)]

            Titles  Year Rating  IMDB_Rating  Netflix
19  Peaky Blinders  2013    18+          8.8        1

In [31]:
df[(df['IMDB_Rating']==8.8) & (df['Rating']== '16+') & (df['Year']== 2013)]

             Titles  Year Rating  IMDB_Rating  Netflix
16  Attack on Titan  2013    16+          8.8        0

In [33]:
df[(df['IMDB_Rating']==8.8) & (df['Rating']== '18+') | (df['Year']== 2013)]

                               Titles  Year Rating  IMDB_Rating  Netflix
2                      Rick and Morty  2013    18+          9.2        0
14                       Black Mirror  2011    18+          8.8        1
16                    Attack on Titan  2013    16+          8.8        0
19                     Peaky Blinders  2013    18+          8.8        1
21                            Vikings  2013    18+          8.5        0
28                             Narcos  2015    18+          8.8        1
31                 Brooklyn Nine-Nine  2013    16+          8.4        0
37                           Hannibal  2013    18+          8.5        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [35]:
df[~ (df['Year']== 2013)]

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+          9.5        1
1                     Game of Thrones  2011    18+          9.3        0
3                                Dark  2017    16+          8.8        1
4                     Stranger Things  2016    16+          8.8        1
5          Avatar: The Last Airbender  2005     7+          9.2        1
6                            Sherlock  2010    16+          9.1        1
7                           Chernobyl  2019    18+          9.4        0
8                             Friends  1994    16+          8.9        0
9                          The Office  2005    16+          8.9        1
10                   Better Call Saul  2015    18+          8.7        1
11                           The Wire  2002    18+          9.3        0
12                       Supernatural  2005    16+          8.4        0
13                              Fargo  2014    18+          8.9        0
14                       Black Mirror  2011    18+          8.8        1
15                   Band of Brothers  2001    18+          9.4        0
17                              House  2004    16+          8.7        0
18                        Money Heist  2017    18+          8.4        1
20                          Mr. Robot  2015    18+          8.5        0
22                       The Sopranos  1999    18+          9.2        0
23                       The Simpsons  1989     7+          8.7        0
24                    The Mandalorian  2019     7+          8.7        0
25                               Lost  2004    16+          8.3        0
26                          Westworld  2016    18+          8.7        0
27               The Umbrella Academy  2019    16+          8.0        1
28                             Narcos  2015    18+          8.8        1
29                     True Detective  2014    18+          9.0        0
30                 Marvel's Daredevil  2015    18+          8.6        1
32                   The Walking Dead  2010    18+          8.2        1
33               Parks and Recreation  2009    16+          8.6        0
34                         Mindhunter  2017    18+          8.6        1
35                         South Park  1997    18+          8.7        0
36                              Suits  2011    16+          8.5        0
38                             Dexter  2006    18+          8.6        0
39                          Community  2009     7+          8.5        0
40                             Fringe  2008    16+          8.4        0
41                      Modern Family  2009    16+          8.4        0
42                The Big Bang Theory  2007    16+          8.1        0
43                            Firefly  2002    16+          9.0        0
44                            Mad Men  2007    16+          8.6        0
45   Fullmetal Alchemist: Brotherhood  2009    18+          9.1        0
46                              Ozark  2017    18+          8.4        1
47                        The Witcher  2019    18+          8.2        1
48                            Lucifer  2016    16+          8.2        1
49  It's Always Sunny in Philadelphia  2005    18+          8.8        0

In [37]:
df[df['Year'].isin([2015])]

                Titles  Year Rating  IMDB_Rating  Netflix
10    Better Call Saul  2015    18+          8.7        1
20           Mr. Robot  2015    18+          8.5        0
28              Narcos  2015    18+          8.8        1
30  Marvel's Daredevil  2015    18+          8.6        1

In [38]:
df[(df['Titles'].str.contains('ot')) | (df['Titles'].str.contains('aul'))]

                              Titles  Year Rating  IMDB_Rating  Netflix
10                  Better Call Saul  2015    18+          8.7        1
15                  Band of Brothers  2001    18+          9.4        0
20                         Mr. Robot  2015    18+          8.5        0
45  Fullmetal Alchemist: Brotherhood  2009    18+          9.1        0

In [39]:
df.at[10,'Year']= None

In [40]:
df

                               Titles    Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008.0    18+          9.5        1
1                     Game of Thrones  2011.0    18+          9.3        0
2                      Rick and Morty  2013.0    18+          9.2        0
3                                Dark  2017.0    16+          8.8        1
4                     Stranger Things  2016.0    16+          8.8        1
5          Avatar: The Last Airbender  2005.0     7+          9.2        1
6                            Sherlock  2010.0    16+          9.1        1
7                           Chernobyl  2019.0    18+          9.4        0
8                             Friends  1994.0    16+          8.9        0
9                          The Office  2005.0    16+          8.9        1
10                   Better Call Saul     NaN    18+          8.7        1
11                           The Wire  2002.0    18+          9.3        0
12                       Supernatural  2005.0    16+          8.4        0
13                              Fargo  2014.0    18+          8.9        0
14                       Black Mirror  2011.0    18+          8.8        1
15                   Band of Brothers  2001.0    18+          9.4        0
16                    Attack on Titan  2013.0    16+          8.8        0
17                              House  2004.0    16+          8.7        0
18                        Money Heist  2017.0    18+          8.4        1
19                     Peaky Blinders  2013.0    18+          8.8        1
20                          Mr. Robot  2015.0    18+          8.5        0
21                            Vikings  2013.0    18+          8.5        0
22                       The Sopranos  1999.0    18+          9.2        0
23                       The Simpsons  1989.0     7+          8.7        0
24                    The Mandalorian  2019.0     7+          8.7        0
25                               Lost  2004.0    16+          8.3        0
26                          Westworld  2016.0    18+          8.7        0
27               The Umbrella Academy  2019.0    16+          8.0        1
28                             Narcos  2015.0    18+          8.8        1
29                     True Detective  2014.0    18+          9.0        0
30                 Marvel's Daredevil  2015.0    18+          8.6        1
31                 Brooklyn Nine-Nine  2013.0    16+          8.4        0
32                   The Walking Dead  2010.0    18+          8.2        1
33               Parks and Recreation  2009.0    16+          8.6        0
34                         Mindhunter  2017.0    18+          8.6        1
35                         South Park  1997.0    18+          8.7        0
36                              Suits  2011.0    16+          8.5        0
37                           Hannibal  2013.0    18+          8.5        1
38                             Dexter  2006.0    18+          8.6        0
39                          Community  2009.0     7+          8.5        0
40                             Fringe  2008.0    16+          8.4        0
41                      Modern Family  2009.0    16+          8.4        0
42                The Big Bang Theory  2007.0    16+          8.1        0
43                            Firefly  2002.0    16+          9.0        0
44                            Mad Men  2007.0    16+          8.6        0
45   Fullmetal Alchemist: Brotherhood  2009.0    18+          9.1        0
46                              Ozark  2017.0    18+          8.4        1
47                        The Witcher  2019.0    18+          8.2        1
48                            Lucifer  2016.0    16+          8.2        1
49  It's Always Sunny in Philadelphia  2005.0    18+          8.8        0

In [42]:
df.at[10,'Year']= None

In [48]:
import numpy as np
df.at[11,'Year']= pd.NA

In [50]:
df[(df['Titles'].str.contains('r',na=True))]

                              Titles    Year Rating  IMDB_Rating  Netflix
0                       Breaking Bad  2008.0    18+          9.5        1
1                    Game of Thrones  2011.0    18+          9.3        0
2                     Rick and Morty  2013.0    18+          9.2        0
3                               Dark  2017.0    16+          8.8        1
4                    Stranger Things  2016.0    16+          8.8        1
5         Avatar: The Last Airbender  2005.0     7+          9.2        1
6                           Sherlock  2010.0    16+          9.1        1
7                          Chernobyl  2019.0    18+          9.4        0
8                            Friends  1994.0    16+          8.9        0
10                  Better Call Saul     NaN    18+          8.7        1
11                          The Wire     NaN    18+          9.3        0
12                      Supernatural  2005.0    16+          8.4        0
13                             Fargo  2014.0    18+          8.9        0
14                      Black Mirror  2011.0    18+          8.8        1
15                  Band of Brothers  2001.0    18+          9.4        0
19                    Peaky Blinders  2013.0    18+          8.8        1
20                         Mr. Robot  2015.0    18+          8.5        0
22                      The Sopranos  1999.0    18+          9.2        0
24                   The Mandalorian  2019.0     7+          8.7        0
26                         Westworld  2016.0    18+          8.7        0
27              The Umbrella Academy  2019.0    16+          8.0        1
28                            Narcos  2015.0    18+          8.8        1
29                    True Detective  2014.0    18+          9.0        0
30                Marvel's Daredevil  2015.0    18+          8.6        1
31                Brooklyn Nine-Nine  2013.0    16+          8.4        0
33              Parks and Recreation  2009.0    16+          8.6        0
34                        Mindhunter  2017.0    18+          8.6        1
35                        South Park  1997.0    18+          8.7        0
38                            Dexter  2006.0    18+          8.6        0
40                            Fringe  2008.0    16+          8.4        0
41                     Modern Family  2009.0    16+          8.4        0
42               The Big Bang Theory  2007.0    16+          8.1        0
43                           Firefly  2002.0    16+          9.0        0
45  Fullmetal Alchemist: Brotherhood  2009.0    18+          9.1        0
46                             Ozark  2017.0    18+          8.4        1
47                       The Witcher  2019.0    18+          8.2        1
48                           Lucifer  2016.0    16+          8.2        1

In [54]:
df[(df['Titles'].str.contains('r',na=False))]

                              Titles    Year Rating  IMDB_Rating  Netflix
0                       Breaking Bad  2008.0    18+          9.5        1
1                    Game of Thrones  2011.0    18+          9.3        0
2                     Rick and Morty  2013.0    18+          9.2        0
3                               Dark  2017.0    16+          8.8        1
4                    Stranger Things  2016.0    16+          8.8        1
5         Avatar: The Last Airbender  2005.0     7+          9.2        1
6                           Sherlock  2010.0    16+          9.1        1
7                          Chernobyl  2019.0    18+          9.4        0
8                            Friends  1994.0    16+          8.9        0
10                  Better Call Saul     NaN    18+          8.7        1
11                          The Wire     NaN    18+          9.3        0
12                      Supernatural  2005.0    16+          8.4        0
13                             Fargo  2014.0    18+          8.9        0
14                      Black Mirror  2011.0    18+          8.8        1
15                  Band of Brothers  2001.0    18+          9.4        0
19                    Peaky Blinders  2013.0    18+          8.8        1
20                         Mr. Robot  2015.0    18+          8.5        0
22                      The Sopranos  1999.0    18+          9.2        0
24                   The Mandalorian  2019.0     7+          8.7        0
26                         Westworld  2016.0    18+          8.7        0
27              The Umbrella Academy  2019.0    16+          8.0        1
28                            Narcos  2015.0    18+          8.8        1
29                    True Detective  2014.0    18+          9.0        0
30                Marvel's Daredevil  2015.0    18+          8.6        1
31                Brooklyn Nine-Nine  2013.0    16+          8.4        0
33              Parks and Recreation  2009.0    16+          8.6        0
34                        Mindhunter  2017.0    18+          8.6        1
35                        South Park  1997.0    18+          8.7        0
38                            Dexter  2006.0    18+          8.6        0
40                            Fringe  2008.0    16+          8.4        0
41                     Modern Family  2009.0    16+          8.4        0
42               The Big Bang Theory  2007.0    16+          8.1        0
43                           Firefly  2002.0    16+          9.0        0
45  Fullmetal Alchemist: Brotherhood  2009.0    18+          9.1        0
46                             Ozark  2017.0    18+          8.4        1
47                       The Witcher  2019.0    18+          8.2        1
48                           Lucifer  2016.0    16+          8.2        1